### ISSUE TITLE
pdiv not implemented

### ISSUE THREAD

**Issue by MilesCranmer** [darioizzo/dcgp#36]
Hi,

Fantastic package! I just started using it and it looks like a very useful alternative to Eureqa ever since they stopped giving out free academic licenses.

I just wanted to note that I'm unable to get the symbolic regression example working as it is (though some modifications fix it). When I declare the kernels, it says that the pdiv kernel is unimplemented:

```
from dcgpy import expression_gdual_vdouble as expression
from dcgpy import kernel_set_gdual_vdouble as kernel_set
from pyaudi import gdual_vdouble as gdual
import pyaudi
from matplotlib import pyplot as plt
import numpy as np
from random import randint
%matplotlib inline

kernels = kernel_set(["sum", "mul", "diff", "pdiv"])()
```

Gives:

```
ValueError: Unimplemented function pdiv for this type
```

I can change pdiv to div and it works, but I was wondering what I was missing to get pdiv working.

Let me know if you'd like more debugging information. I'm installed from pip on Python 3.7.3, with:
```
    dcgpy.__version__: '1.2.1'
    pyaudi.__version__: '1.6.4'
    numpy.__version__: '1.16.2'
    sympy.__version__: '1.4'
```
Thanks!
Miles

**Comment by darioizzo** [comment]
@MilesCranmer 
pdiv is not implemented for gduals as its derivatives are undefined and typically mess up the whole computations.

We could implement some type of protected derivation .... but we are not sure it would make sense at the end .... In case you have ideas let us have them.

You can use (and its also much faster)  ```from dcgpy import expression_double as expression``` if you do not need derivatives.

Did you know you can play around a small version of dcgp here: https://esa.github.io/dcgp-web/ ?

Dario
