### ISSUE TITLE
Parallelism

### ISSUE THREAD

**Issue by MilesCranmer** [darioizzo/dcgp#37]
Hi @darioizzo,

I was wondering if there were any options for parallelism in dCGPy for symbolic regression? I thought about parallelizing the following loops:

```
for i in range(offsprings):
            dCGP.set(best_chromosome)
            cumsum=0
            dCGP.mutate_active(i+1)
            fit, constant[i] = err2(dCGP, x, yt, best_constants)
            fitness[i] = fit
            chromosome[i] = dCGP.get()
```
in the `run_experiment` code in Python, but it appears dCGP is a global var.

Thanks,
Miles

**Comment by darioizzo** [comment]
What code ```run_experiment``` do you refer too? 

In any case, Parallelism can be set when computing the loss (MSE) over a batch of data via the method loss of an expression.
What you are after here is parallelism for computing different expressions (i.e. chromosomes) in parallel. That too can be achieved via standard python parallelism tools.

**Comment by darioizzo** [comment]
In the next release, we are woking on the integration of dcgp with pagmo and will get two more parallelism options
1) computing the loss in parallel on members of a population (ES strategy)
2) computing ES algorithm is parallel and have migration among them 

Will close this issue as outdated. Feel free to reopen if you are not happy with the direction we are going.
