### ISSUE TITLE
expression.set_weight() for weighted expressions does not respect the input_id

### ISSUE THREAD

**Issue by hejung** [darioizzo/dcgp#56]
Using `expression.set_weight(node_id, input_id, w)` will always set the weight at input_id=0 of node_id=node_id to w.

Minimal working example:
```python
import dcgpy

expr = dcgpy.expression_weighted_double(1, 1, 1, 1, 2, 2, dcgpy.kernel_set_double(['sum', 'diff', 'div', 'mul'])())
print(expr.get_weights())  # prints [1.0, 1.0]
expr.set_weight(0, 1, 0.5)  # should set the second weight to 0.5
print(expr.get_weights())  # prints [0.5, 1.0]
```

If I see it right the issue is that in the C++ function we get the node_id but do not add the input_id when constructing the index to the weight vector.

If you agree that this is the problem and if it helps, I can prepare a pull request for that.

**Comment by darioizzo** [comment]
sure, its a bit I do not work on expression weighted so you may be right. If  you want to prepare a PR add a test with the intended behaviour too.

**Comment by hejung** [comment]
I had previously only set the whole weight vector and lately I been using the (new) symbolic regression together with pagmo. I only noticed the bug in the single weight functions when doing checks of my simplify-fix :)
