### ISSUE TITLE
Defining a custom kernel in C++

### ISSUE THREAD

**Issue by Armavica** [darioizzo/dcgp#65]
Hello,
I am sorry if I am missing something obvious but I have a lot of trouble to define my custom kernel. I would like to use the Lambert W function as a kernel. It is [implemented in boost](https://www.boost.org/doc/libs/1_72_0/libs/math/doc/html/math_toolkit/lambert_w.html).
I tried to adapt the [first C++ example](http://darioizzo.github.io/dcgp/tutorials/cpp/cpp_symbolic_regression_1.html) by adding the kernel as specified in the documentation for [kernel](http://darioizzo.github.io/dcgp/docs/cpp/kernel.html) and in the one for [kernel_set](http://darioizzo.github.io/dcgp/docs/cpp/kernel_set.html) as following:

``` C++
#include <boost/math/special_functions/lambert_w.hpp>
// [...]

template <typename T>
inline T my_lambertw(const std::vector<T> &in) {
    return boost::math::lambert_w0(in[0]);
}

inline std::string print_my_lambertw(const std::vector<std::string> &in) {
    std::string retval(in[0]);
    return "Lw(" + retval + ")";
}

int main() {
    // [...]
    kernel<double> f(my_lambertw<double>, print_my_lambertw, "my_lambertw");
    kernel_set<double> kernels({"sum", "diff", "mul", "pdiv"});
    kernels.push_back(f);
    symbolic_regression udp(X, Y, 1, 20, 21, 2, kernels(), n_eph);
    // [...]
}
```

The compilation succeeds but at execution the program fails with 

```
terminate called after throwing an instance of 'std::invalid_argument'
  what(): Unimplemented function my_lambertw for this type
Aborted
```

The error makes me think that the kernel should maybe be implemented for dual numbers as well? But I don't know how to do it.

Could you please help me to understand the issue? When I understand how to do it, I would be very happy to complete the documentation or write a short example exhibiting custom kernels to help future users.
Thank you very much in advance!

**Comment by darioizzo** [comment]
The addition of custom kernels is a poorly documented part of the code, indeed. And PRs are welcome there.

The class ```kernel_set<double>``` is only a helper class that facilitates the construction of a ```std::vector<dcgp::kernel<double>>``` including the kernels shipped in dcgp. For custom kernels, you have to add manually the new kernel to the :
```
kernel_set<double> kernels({"sum", "diff", "mul", "pdiv"});
auto kernel_v = kernels();
kernel_v.push_back(f);
symbolic_regression udp(X, Y, 1, 20, 21, 2, kernel_v, n_eph);
```

Let me know if this works, and yes please contribute! An example would be very welcome.

**Comment by darioizzo** [comment]
You are adding a special function as a kernel. This will not work for gdual computations as the third party dependency audi does not know how to comoute lambertw on a gdual.
