### ISSUE TITLE
make dcgp expressions available in python

### ISSUE THREAD

**Issue by CoolRunning** [darioizzo/dcgp#72]
There should be a way to retrieve individuals of a population of `symbolic_regression` udps as `expression_double`, `expression_gdual_double`, etc.

Right now, the chromosome is accessible in raw by `pop.get_x()`, but expressions would be easier to work with.

**Comment by darioizzo** [comment]
It is possigle to get back an ```expression_double``` fairly easily. Something like
```
udp.get_expression_double()
```
is it necessary also to provide
```
udp.get_expression_gdual_double()
```
?

**Comment by CoolRunning** [comment]
The double expression already helps. At the moment, I do not need the gduals, but it might be a nice to have eventually.

**Comment by darioizzo** [comment]
closing this .... if needed feel free to reopen
