### ISSUE TITLE
obake not found

### ISSUE THREAD

**Issue by shah314** [darioizzo/dcgp#73]
I was missing the environment creation in the conda command. Now I am able to install everything and run the python tests referenced on the repository. Thank you very much for the help. I think you should change the installation command in the README to the one that you mentioned (that includes the environment creation). I am not very familiar with conda and there could be readers who are also not experts.

But I am still unable to build the git package. The error is as follows:

<pre>
CMake Error at /Users/shah/Documents/anaconda/anaconda3/envs/dcgpy/lib/cmake/audi/audi-config.cmake:9 (find_package):
  By not providing "Findobake.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "obake", but
  CMake did not find one.

  Could not find a package configuration file provided by "obake" with any of
  the following names:

    obakeConfig.cmake
    obake-config.cmake

  Add the installation prefix of "obake" to CMAKE_PREFIX_PATH or set
  "obake_DIR" to a directory containing one of the above files.  If "obake"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:193 (find_package)
</pre>

**Comment by bluescarni** [comment]
Can you try to invoke CMake passing the ``CMAKE_PREFIX_PATH`` variable? This needs to point to the path of your conda environment. E.g.,

```
cmake ../ -DCMAKE_PREFIX_PATH=/Users/shah/Documents/anaconda/anaconda3/envs/dcgpy
```

**Comment by shah314** [comment]
That gives me the same error. I tried installing obake again but it says it is already installed.

<pre>
(dcgpy) $ sudo conda install -n dcgpy obake
Password:
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

(dcgpy) $ 
</pre>

**Comment by bluescarni** [comment]
obake is split into two packages, ``obake`` (the runtime library) and ``obake-devel`` (headers, CMake files, etc.). If you want to compile something that uses obake, you also need the ``obake-devel`` package installed.

**Comment by shah314** [comment]
I see, that fixed the error. Another error:

<pre>
CMake Error at /Users/shah/Documents/anaconda/anaconda3/envs/dcgpy/lib/cmake/Boost-1.72.0/BoostConfig.cmake:185 (boost_find_component):
  boost_find_component Macro invoked with incorrect arguments for macro
  named: boost_find_component
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/FindBoost.cmake:444 (find_package)
  cmake_modules/DCGPFindBoost.cmake:5 (find_package)
  CMakeLists.txt:183 (include)
</pre>

**Comment by bluescarni** [comment]
This is a bug with Boost's CMake files. Try adding the ``-DBoost_NO_BOOST_CMAKE=ON`` option when invoking CMake.

**Comment by shah314** [comment]
Build succeeded and tests passed. Can you please document these issues in the README? Thank you.

**Comment by shah314** [comment]
@darioizzo @bluescarni Can you please document this in the README?

@Ohjeah

**Comment by darioizzo** [comment]
instructions on how to use conda to install third party dependencies now on the readme.
