### ISSUE TITLE
Building examples

### ISSUE THREAD

**Issue by shah314** [darioizzo/dcgp#76]
I am trying to build the C++ examples. Here is the cmake command I am using:

<pre>
cmake -DCMAKE_PREFIX_PATH=/Users/shah/Documents/anaconda/anaconda3/envs/dcgpy/ -DCMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES=/Users/shah/Documents/anaconda/anaconda3/envs/dcgpy/include/ .
</pre>

The Eigen library is installed in an eigen3 directory, and it appears that it is unable to find headers inside the eigen3/Eigen/ directory.

<pre>
/Users/shah/Documents/anaconda/anaconda3/envs/dcgpy/include/audi/invert_map.hpp:4:10: fatal error: 
      'Eigen/Dense' file not found
#include <Eigen/Dense>
         ^~~~~~~~~~~~~
</pre>

**Comment by shah314** [comment]
As a workaround, I copied the include/eigen3/Eigen directory to the include directory and it appears that compilation works. But I get a linker error:

<pre>
(dcgpy) examples shah$ make
[  4%] Building CXX object CMakeFiles/hamiltonian_kepler.dir/hamiltonian_kepler.o
[  9%] Linking CXX executable hamiltonian_kepler
<b>ld: library not found for -ldcgp</b>
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [hamiltonian_kepler] Error 1
make[1]: *** [CMakeFiles/hamiltonian_kepler.dir/all] Error 2
make: *** [all] Error 2
</pre>

**Comment by darioizzo** [comment]
Note that in the conda package manager we do not support a C++ development environment, and thats why the package is called ```dcgp-python```. It is nevertheless possible and easy to do what you are trying to do, for example try out these commands:

```
conda create -n dcgpy_review python=3.7 dcgp-python pagmo-devel audi obake-devel
```

Then, in a build folder inside the cloned cgp repository, type:

```
cmake -DBoost_NO_BOOST_CMAKE=ON -DCMAKE_INSTALL_PREFIX=/path_to/miniconda/envs/dcgpy_review/ -DCMAKE_PREFIX_PATH=/path_to/miniconda/envs/dcgpy_review/ -DDCGP_BUILD_EXAMPLES=on -DDCGP_BUILD_TESTS=off ../
```

**Comment by shah314** [comment]
That worked. Thanks. 

I am trying to build getting_started.cpp using the instructions provided here:
https://darioizzo.github.io/dcgp/quickstart.html#c

I get the following cmake error. Thoughts?

<pre>
CMake Error at /Users/shah/Documents/anaconda/anaconda3/envs/dcgpy/lib/cmake/pagmo/FindNLOPT.cmake:8 (if):
  if given arguments:

    "NOT" "header" "IN_LIST" "_NLOPT_ALLOWED_COMPONENTS"

  Unknown arguments specified
Call Stack (most recent call first):
  /Users/shah/Documents/anaconda/anaconda3/envs/dcgpy/lib/cmake/pagmo/pagmo-config.cmake:12 (find_package)
  /Users/shah/Documents/anaconda/anaconda3/envs/dcgpy/lib/cmake/dcgp/dcgp-config.cmake:11 (find_package)
  CMakeLists.txt:5 (find_package)
</pre>

**Comment by darioizzo** [comment]
@shah314 this is a cmake issue, in the `CMakeLists.txt` project try to add the line:
```
    cmake_policy(SET CMP0057 NEW)
```
should fix it. If  you confirm I will add it to the docs (although its a cmake version dependant fix, I guess).

**Comment by darioizzo** [comment]
Actually i think its enough to change the required cmake version as suggested to me by @bluescarni 

```
    cmake_minimum_required(VERSION 3.8)
```

**Comment by darioizzo** [comment]
Fixed

**Comment by shah314** [comment]
This works. I also see you updated the docs. Thank you.
