### ISSUE TITLE
Python Getting Started is broken

### ISSUE THREAD

**Issue by Ohjeah** [darioizzo/dcgp#77]
Invoking https://github.com/darioizzo/dcgp/blob/master/doc/examples/getting_started.py

yields

```
Traceback (most recent call last):
  File "getting_started.py", line 20, in <module>
    print("Expression:", ex(in_sym)[0])
NameError: name 'in_sym' is not defined
```

and after defining `in_sym = ["x"]` the sympy module cannot be found.

Where do I see the requirements.txt or similar list of python dependencies which will be installed and do you have additional dependencies to be installed for the examples to work?

**Comment by darioizzo** [comment]
Its a typo. Sorry no idea how it got there:. Fixed now (in master), can you confirm?

**Comment by Ohjeah** [comment]
Works for me, however I had to manually install `sympy` and `graphviz`. Should I make a new issue for this?

**Comment by darioizzo** [comment]
In theory for the getting started are not needed, those are optional dependencies. I would like to reproduce. You installed the conda packages for dcgp-python and then tried to run the getting started?

**Comment by Ohjeah** [comment]
I installed as follows: `conda install dcgp-python -c conda-forge`

Anyway I'd like to see a transparent list of dependencies and their versions. As I user I'd want to make sure that  dcgpy fits my projects environment.

**Comment by darioizzo** [comment]
Sure, but sympy and graphviz are not dependencies, they are optional. Thats why I am surprised you get errors. I am trying to understand whats going on. The error appears if you run ``getting_started.py``?

**Comment by darioizzo** [comment]
@Ohjeah I tried to reproduce and I cannot get the issue reported here. Just to clarify: dcgpy works without symy or graphviz. Some functionalities (i.e. some methods of specific classes, like simplify) do need the dependencies. In this case when called they should report a text similar to:
```
"Failed to import the required module sympy"
```

**Comment by Ohjeah** [comment]
Yes this for the `getting_started.py`. Without sympy, it simply crashes with an `ImportError`. The requirements list (including the optional requirements) need to be stated somewhere and in case of python they should be installable with a package manager.

**Comment by darioizzo** [comment]
Ok found the problem. I have updated the docs to include the optional dependencies and modified the conda package as to install them explicitly.
