### ISSUE TITLE
Evolve a neural network

### ISSUE THREAD

**Issue by shah314** [darioizzo/dcgp#80]
Is it possible to evolve the topology of a neural network through mutation? (I know the implementation does not do crossover) Maybe I am not following the python code correctly, but it appears that in the [feed forward neural network example](https://darioizzo.github.io/dcgp/notebooks/dCGPANNs_for_function_approximation.html), the following creates a fixed topology. If this was possible, the implementation could be very powerful (the code as it is is also quite powerful).
<pre>
dcgpann = dcgpy.encode_ffnn(2,1,[50,20,10],["sig", "sig", "sig", "sum"], 5)
</pre>

**Comment by shah314** [comment]
Maybe this can be done using the symbolic regression functionality. So closing this issue.

**Comment by darioizzo** [comment]
Absolutely! The neural network topology can be evolved ... some of the examples show how to do so.

**Comment by shah314** [comment]
[Found it](http://darioizzo.github.io/dcgp/notebooks/An_intro_to_dCGPANNs.html). Thank you!

**Comment by shah314** [comment]
Is there a method (like the following for symbolic regression) called "evolve" for neural networks that does some combination of SGD and mutation to evolve a neural network? i.e. an end to end genetic programming routine for neural networks.

<pre>
pop = algo.evolve(pop)
</pre>

Would it be useful?

**Comment by shah314** [comment]
What I am trying to do is use expression_ann and use the algo.evolve() method. But I get a notimplementederrror.

<pre>
NotImplementedError: the mandatory 'fitness()' method has not been detected in the user-defined Python problem 'd-CGP Expression:
</pre>

**Comment by shah314** [comment]
I came across this paper a few months back. Just posting for your reference:
https://arxiv.org/pdf/1906.04358.pdf

**Comment by darioizzo** [comment]
it unclear what you are trying to do. But you cannot pass an expression_ann as udp to pagmo. You need to write your own udp respecting the pagmo format. 

On the weight agnostic networks i believe @CoolRunning made experiment using dcgp and pagmo .... maybe he has comments.

**Comment by CoolRunning** [comment]
Hello!

Indeed, you have to write your own udp in pygmo which takes a dcgpann upon construction. Internally, in the fitness function for a reinforcement learning task like the one with the bipedwalker, you would 

1. set the dcgpann by the chromosome `x` provided to `def fitness(self, x)`
2. instantiate the simulation environment, run the walker with the dcgpann predicting the controls and return the corresponding reward as fitness-vector.

So far I had mixed results applying this technique. On the plus side, dCGPANN is capable of expressing complex walking behavior but finding it with evolution is difficult/unstable. Without heavy boostrapping, the results are not competitive enough for my taste. However, this is still ongoing research. :)
