### ISSUE TITLE
[BUG] Issues with tutorial

### ISSUE THREAD

**Issue by MilesCranmer** [darioizzo/dcgp#83]
Nice looking package! I'm eager to try it out as an alternative to Eureqa. Here are the issues I am facing:

**Describe the bug**
2 issues:

- [x] Complained about missing libpagmo.so.1 and libipopt.so.1.
    - I fixed (hopefully) by symlinking libpagmo.so.3 and libipopt.so.3 (which are the installed packages by conda-forge)
- [ ] I see the following issues when running the Python tutorial: http://darioizzo.github.io/dcgp/notebooks/symbolic_regression_1.html
```python
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
<ipython-input-9-0a362e511eb6> in <module>
      1 ss = dcgpy.kernel_set_double(["sum", "diff", "mul", "pdiv"])
      2 udp = dcgpy.symbolic_regression(points=X, labels=Y, kernels=ss())
----> 3 uda  = dcgpy.es4cgp(gen=10000, max_mut=4)
      4 prob = pg.problem(udp)
      5 algo = pg.algorithm(uda)
ArgumentError: Python argument types in
    es4cgp.__init__(es4cgp)
did not match C++ signature:
    __init__(_object*, unsigned int gen=1, unsigned int mut_n=1, double ftol=0.0001, bool learn_constants=True, unsigned int seed)
    __init__(_object*, unsigned int gen=1, unsigned int mut_n=1, double ftol=0.0001, bool learn_constants=True)
    __init__(_object*)
```

**To Reproduce**
conda-forge install with Python 3.7, then run the tutorial.

**Environment (please complete the following information):**
 - OS: CentOS Linux release 7.8.2003
 - Installation method: conda-forge
 - Version: conda 4.8.3; python 3.7; gcc 8.3.0

**Comment by darioizzo** [comment]
Thanks @MilesCranmer. Keep on mind that we are still developing the package and while the API is foreseen to only have minor changes, the performances of the evolution will be improving radically in the next versions.

As for your bug report, did you install the dcgp-python package from conda? Or you installed and compiled the code yourself?

In case you installed the conda dcgp-python package, can you report here the exact commands you used to create the conda environment and to install the package?

**Comment by MilesCranmer** [comment]
Thanks, no problem at all. I installed dcgp-python with `conda install -c conda-forge dcgp-python`. I installed it in my existing environment. I could try a new env if you think that would be better, but my intuition tells me this bug is dependent on other things.

Maybe I should try installing from source?

**Comment by darioizzo** [comment]
I would like you to try from a fresh env following the instructions on the
online docs.

Conda tests all packages and the only reason for this failing is some weird
package dep that is forcing in your current env the installation of old and
incompatible versions of some packages ...

**Comment by MilesCranmer** [comment]
Awesome, it works!! Thanks for your help. My intuition was very wrong, sorry about that.

Here is the env I set up, which worked:
```
conda create --name dcgpy --channel conda-forge python=3.7 numpy scipy \
matplotlib cython h5py pyfftw notebook tqdm jupyter jupyterlab mpi4py openmpi \
astropy ipywidgets dcgp-python -y
```
