### ISSUE TITLE
[DOCS] Hyperparameter tuning advice

### ISSUE THREAD

**Issue by MilesCranmer** [darioizzo/dcgp#85]
Hi @darioizzo,

I was wondering if you had any hyperparameter tuning advice for symbolic regression? I've read descriptions of hyperparameters, but don't have much intuition for what they should be chosen to be.

For a given multi-objective symbolic regression problem, how should I select the following?

- cols
- rows
- levels_back
- gen
- max_mut
- size (for population)

I've started with the ones given in the examples. But I have no intuition for how to tune them to a different problem. Furthermore, if I encounter one of the following situations, how should I re-tune my parameters?

- Expressions are too simple
or
- Expressions are overcomplicated, but still don't find the true equation

Thanks!
Miles

**Comment by darioizzo** [comment]
Advise is tricky to give in general. I would start using the symbolic_regression udp as in the examples:
```
symbolic_regression udp(X, Y, 1u, 16u, 17u, 2u, kernel_set<double>({"sum", "diff", "mul", "pdiv"})(), n_eph, true, 0u, "MSE");
```

and use momes to deal with the expression overcomplication.
