### ISSUE TITLE
mes4cgp takes up all cpu cores [BUG]

### ISSUE THREAD

**Issue by CoolRunning** [darioizzo/dcgp#87]
**Describe the bug**
In contrast to `es4cgp`, which can be constraint to run single-core by setting `parallel_batches = 0` in the corresponding symbolic regression udp, the memetic variant `mes4cgp` does not have this option and reserves all cpus available. This makes it impossible/hard to deploy fairly on large compute servers.

**To Reproduce**
The behavior should be reproducible simply be running some tutorial code.

**Expected behavior**
`mes4cgp` should respect `parallel_batches` similar to `es4cgp`.

**Environment (please complete the following information):**
 - OS: archlinux
 - Installation method: conda
 - Version: dcgp-python 1.5

**Comment by darioizzo** [comment]
Cannot reproduce. 

Both ```es4cgp``` and ```mes4cgp``` do not have any parallelism (except the bfe mechanism of pagmo which can be activated only on es4cgp). Parallelism is implemented at the udp level and acts in a symmetric way on both.

If you can provide a minimal code snippet I can have a deeper look.

**Comment by CoolRunning** [comment]
This was a bit more difficult to reproduce than initially expected, as the parallelism only becomes apparent for larger collections of data. Executing the following snippet takes about a minute during which you should be able to observe CPU saturation on all cores:

```python
import dcgpy
import pygmo as pg
import numpy as np

def main():
    X, Y = dcgpy.generate_sinecosine()
    
    # the bug becomes only visible for larger datasets
    # without the following two lines it would be hardly noticeable
    X = np.vstack(20 * [X])
    Y = np.vstack(20 * [Y])
    
    kernelset = dcgpy.kernel_set_double(["sum", "diff", "mul", "pdiv", "log", "sin", "exp"])()

    udp = dcgpy.symbolic_regression(
        points = X, labels = Y, 
        kernels=kernelset,
        rows = 10,
        cols = 20,
        n_eph = 4,
        parallel_batches = 0,
        levels_back = 10)

    prob = pg.problem(udp)

    # the bug can be observed for this uda
    uda  = dcgpy.mes4cgp(gen = 30000, max_mut = 4)
    
    # using the following uda avoids the bug
    #uda  = dcgpy.es4cgp(gen = 30000, max_mut = 4, learn_constants=True)
    
    alg = pg.algorithm(uda)
    alg.set_verbosity(3000)

    pop = pg.population(prob, 4)
    pop = alg.evolve(pop)
    
    print('done.')

if __name__ == '__main__':
    main()
```

**Comment by bluescarni** [comment]
Is ``mes4cgp`` using the truncated polynomial algebra? If so, what you might be seeing is the parallelisation of polynomial multiplication.

**Comment by CoolRunning** [comment]
I think the parallelism comes from code running for multiple ephemeral constants, as with `n_eph = 1` it is also not visible.

**Comment by darioizzo** [comment]
Thats a very weird observation. There is nothing in the way eph consants are dealt with that refers to parallelism ... try to confirm your observation with the new code and produce  a minimal example?

**Comment by darioizzo** [comment]
the addition of the global disable parallelism functions solves this. #92
